### PR TITLE
Treat literal expressions as static

### PR DESCRIPTION
**Pull request by jridgewell**
Also adds to the README and sets up the Travis config (still needs to be enabled).

### CODE REVIEW

**Comment by thejameskyle** [comment]
@jridgewell Do you have a username on npm?

**Comment by thejameskyle** [comment]
@jridgewell if you give me your username, I'll add you to npm and you can merge/build/publish releases yourself.

**Comment by jridgewell** [comment]
It's [@jridgewell](https://www.npmjs.com/~jridgewell).

**Comment by thejameskyle** [comment]
Cool, added. 

You only have to run `npm run push` to release. There are steps that will walk you through it. Also, if it hangs after build:

```shell
> babel-plugin [ 'build' ]
> babel [ 'src', '--out-dir', 'lib', '--copy-files' ]
src/helpers.js -> lib/helpers.js
src/index.js -> lib/index.js
# hangs forever
```

then just ctrl+c it and it will continue. This was just fixed in 5.8.4.

**Pull request merged**
